### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by helgee** [helgee/plyades#2]
- [X] Kepler solver
- Numerical orbits
  - [X] Propagator
    - [ ] Event detection
    - [ ] Stopping conditions
  - Force model
    - [X] Uniform gravity potential
    - [X] J2 non-uniform gravity potential
    - [ ] Atmospheric drag
    - [ ] Solar radiation pressure
    - [ ] Thrust
- Frame transformations
  - [X] Origin translations
  - [ ] Rotations
